### ISSUE TITLE
tel: links get crawled

### ISSUE THREAD

**Issue by staabm** [codeguy/arachnid#16]
Despite beeing blacklisted in `checkIfCrawlable` tel links get crawled.

tested via 

``` php
$crawler = new \Arachnid\Crawler('https://www.handyflash.de/', 3);
$crawler->traverse();
```

in the apache accesslog a hit like

```
www.handyflash.de:443 213.XXX.YYY.ZZZ - - [10/Jun/2016:12:24:42 +0200] "GET /tel:+4923199778877 HTTP/1.1" 404 37312 "-" "Symfony2 BrowserKit" 0
```

is recorded

**Comment by zrashwani** [comment]
This bug is solved now, 
verified in this test https://github.com/codeguy/arachnid/blob/master/tests/src/CrawlerTest.php#L381

**Comment by codeguy** [comment]
@zrashwani I don't have time to maintain this project. Would you like me to transfer ownership of it to you?

**Comment by zrashwani** [comment]
@codeguy yes, I am planning to continue maintaining the project, so please transfer ownership to me
