### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by emilhauk** [codeguy/arachnid#18]
I tried to pull this through composer, but it was flagged abandoned. Just checking if this was intentional :)

**Comment by codeguy** [comment]
Unfortunately, it is for now. It's looking for someone to take it over as I don't have time or interest to work on it further.

/cc @zrashwani Any interest?

**Comment by zrashwani** [comment]
yes @codeguy , I will maintain this project, you can transfer ownership to me

**Comment by codeguy** [comment]
Great. Doing that now.

**Comment by codeguy** [comment]
@zrashwani You need  to delete  your fork before I can transfer.

**Comment by zrashwani** [comment]
@codeguy done, just deleted

**Comment by codeguy** [comment]
Transfer initiated. You'll want to claim this on Packagist too so that it is not marked as abandoned.

**Comment by emilhauk** [comment]
Nice, thank you guys :)
