### ISSUE TITLE
Update Goutte dependency version

### ISSUE THREAD

**Issue by ollietreend** [codeguy/arachnid#8]
Hi,

I'm trying to use Goutte and Arachnid together to crawl and then scrape content from a website. I've installed Goutte which currently sits at version 3.1. I'm unable to install Arachnid alongside this version of Goutte because it requires Gouttee version ~1.

Is there any chance we can get the `composer.json` requirements either updated, or loosened to just accept any version of Goutte? Or is there a reason for this library to require that version of Goutte?

Arachnid's composer.json requirements:

```
"require": {
    "php": ">=5.4.0",
    "fabpot/goutte": "~1"
}
```

My composer.json requirements, using latest stable version of Goutte:

```
"require": {
    "fabpot/goutte": "^3.1"
}
```

Thanks

**Comment by zrashwani** [comment]
Hello Ollie,
I have amended the composer.json requirement to work with latest version of Goutte,
you can use release 1.0.3
https://github.com/codeguy/arachnid/releases/tag/1.0.3

thank you for pointing to this,

Regards,
